version: 0.2
run-as: Summer2023

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd user-service
      - npm install -g serverless
      - npm install
  build:
    commands:
      - serverless deploy --stage dev

cache:
  paths:
    - user-service/node_modules