service: user-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false # dont keep versions
  stage: "dev"
  region: "us-east-1"
  httpApi:
    cors: true

functions:
  register:
    handler: app/handler.Register
    events:
      - httpApi:
          path: /register
          method: post

  login:
    handler: app/handler.Login
    events:
      - httpApi:
          path: /login
          method: post


custom:
  autoswagger:
    title: 'User Service'
    apiType:  'httpApi'

package:
  exclude:
    - README.md
    - .build

plugins:
  - serverless-auto-swagger   # https://{your-url-domain}/swagger
  - serverless-offline
  - serverless-plugin-typescript
